# Generated by Django 2.1 on 2018-08-22 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='歌曲名称')),
                ('author', models.TextField(max_length=50, verbose_name='创作者')),
                ('pic', models.URLField(blank=True, null=True, verbose_name='封面链接')),
                ('url', models.URLField(verbose_name='歌曲链接')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('show_desc', models.BooleanField(default=True, verbose_name='在正文显示描述')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('show', models.CharField(default='<built-in function id>', max_length=10, verbose_name='url显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide')),
                ('pin', models.BooleanField(default=False, verbose_name='Pin')),
                ('draft', models.BooleanField(default=False, verbose_name='草稿')),
                ('can_comment', models.BooleanField(default=True, verbose_name='是否开放评论区')),
                ('body', models.TextField(verbose_name='正文')),
                ('author', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Music')),
            ],
            options={
                'ordering': ['-pin', 'hide', 'draft', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
