# Generated by Django 2.1 on 2018-08-22 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pin', '-create_time']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='show',
        ),
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.CharField(max_length=50, verbose_name='创作者'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
