# Generated by Django 2.1 on 2018-08-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180822_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='隐藏'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pin',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
    ]
