# Generated by Django 2.1 on 2018-08-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180823_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.BooleanField(default=False, verbose_name='TOC'),
        ),
        migrations.AlterField(
            model_name='post',
            name='can_comment',
            field=models.BooleanField(default=True, verbose_name='开放评论区'),
        ),
    ]
