# Generated by Django 2.1 on 2018-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180823_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cc',
            field=models.BooleanField(default=True, verbose_name='使用CC授权'),
        ),
        migrations.AddField(
            model_name='post',
            name='has_music',
            field=models.BooleanField(default=True, verbose_name='Has Music'),
        ),
    ]
