# Generated by Django 2.1 on 2018-08-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20180823_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='称呼')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('body', models.TextField(verbose_name='留言')),
                ('hide', models.BooleanField(default=False, verbose_name='隐藏')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post', verbose_name='文章')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
